import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ProductDTOResponse, UnitOfMeasure, fetchProducts } from "../../services/product/productService";
import { CommercialUnitGroup, ContentResolutionAction, confirmFiscalReceiptImport, fetchFiscalReceiptImport, FiscalReceiptImportResponse, FiscalResolutionAction, FiscalReviewGroup, fiscalReceiptErrorMessage, resolveFiscalReviewGroup } from "../../services/fiscalReceipt/fiscalReceiptService";
import FiscalQuantityHelpModal from "./FiscalQuantityHelpModal";
import "../../styles/pages/FiscalReceipt/FiscalReceiptReview.css";

const units = Object.values(UnitOfMeasure);
const money = (v: number) => Number(v || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const decimal = (v: number) => Number(v || 0).toLocaleString("pt-BR", { maximumFractionDigits: 3 });
const stocks = (a?: FiscalResolutionAction | "") => a === "USE_EXISTING_PRODUCT" || a === "CREATE_TEMPORARY_PRODUCT";
type Selected = Pick<ProductDTOResponse, "id" | "name" | "brand" | "gtin" | "quantityPerUnit" | "unit">;
type Draft = { units: string; content: string; unit: UnitOfMeasure | ""; saveFuture: boolean; learned: boolean; changed: boolean };
const draft = (u: CommercialUnitGroup): Draft => ({ units: String(u.unitsPerCommercialUnit || 1), content: (u.contentQuantityPerUnit ?? u.contentEvidenceComparison?.suggestedQuantity)?.toString() || "", unit: u.contentUnit || u.contentEvidenceComparison?.suggestedUnit || "", saveFuture: !u.learnedSuggestion, learned: !!u.learnedSuggestion, changed: false });

const GroupEditor: React.FC<{ importId:number; group:FiscalReviewGroup; saved:(r:FiscalReceiptImportResponse)=>void; cancel:()=>void; help:()=>void }> = ({importId,group,saved,cancel,help}) => {
 const [action,setAction]=useState<FiscalResolutionAction|"">(group.resolutionAction||"");
 const [selected,setSelected]=useState<Selected|null>(group.matchedProductId ? {id:group.matchedProductId,name:group.matchedProductName||"Produto",brand:group.matchedProductBrand||"",gtin:group.gtin||"",quantityPerUnit:group.matchedProductQuantityPerUnit||0,unit:group.matchedProductUnit as UnitOfMeasure}:null);
 const [drafts,setDrafts]=useState<Record<string,Draft>>(()=>Object.fromEntries(group.commercialUnitGroups.map(u=>[u.commercialUnit,draft(u)])));
 const [contentResolution,setContentResolution]=useState<ContentResolutionAction|undefined>(group.commercialUnitGroups.find(u=>u.contentEvidenceComparison?.selectedResolution)?.contentEvidenceComparison?.selectedResolution);
 const [tempName,setTempName]=useState(group.temporaryProductDraft?.name||group.description); const [tempBrand,setTempBrand]=useState(group.temporaryProductDraft?.brand||group.parsedDescriptor?.brand||"");
 const [name,setName]=useState(""); const [gtin,setGtin]=useState(""); const [results,setResults]=useState<ProductDTOResponse[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const update=(unit:string, patch:Partial<Draft>)=>setDrafts(old=>({...old,[unit]:{...old[unit],...patch,changed:true}}));
 const search=async()=>{setBusy(true);try{setResults((await fetchProducts({page:0,name:name||undefined,gtin:gtin||undefined})).content);}catch(e){setError(fiscalReceiptErrorMessage(e));}finally{setBusy(false);}};
 const needs=(u:CommercialUnitGroup)=>stocks(action)&&!u.directMeasurement&&!(u.commercialUnit==="UN"&&action==="USE_EXISTING_PRODUCT"&&selected?.quantityPerUnit&&selected?.unit&&!drafts[u.commercialUnit]?.changed);
 const save=async()=>{if(!action)return setError("Escolha uma decisão para este produto.");if(action==="USE_EXISTING_PRODUCT"&&!selected)return setError("Selecione um produto existente.");if(group.commercialUnitGroups.some(u=>u.contentEvidenceComparison?.status==="CONFLICT")&&!contentResolution)return setError("Escolha como resolver a diferença de conteúdo.");const required=group.commercialUnitGroups.filter(needs);if(required.some(u=>!drafts[u.commercialUnit]?.content||!drafts[u.commercialUnit]?.unit||Number(drafts[u.commercialUnit]?.units)<=0||Number(drafts[u.commercialUnit]?.content)<=0))return setError("Preencha a conversão de cada unidade comercial.");setBusy(true);setError("");try{saved(await resolveFiscalReviewGroup(importId,group.reviewGroupId,{resolutionAction:action,productId:action==="USE_EXISTING_PRODUCT"?selected?.id:undefined,contentResolutionAction:contentResolution,temporaryProductDraft:action==="CREATE_TEMPORARY_PRODUCT"?{name:tempName,brand:tempBrand}:undefined,conversions:required.map(u=>{const d=drafts[u.commercialUnit];return{commercialUnit:u.commercialUnit,unitsPerCommercialUnit:Number(d.units),contentQuantityPerUnit:Number(d.content),contentUnit:d.unit as UnitOfMeasure,ruleAction:d.learned&&!d.changed?"USE_LEARNED":d.saveFuture?"UPDATE_LEARNED":"CURRENT_ONLY"};})}));}catch(e){setError(fiscalReceiptErrorMessage(e));}finally{setBusy(false);}};
 return <div className="fiscal-editor">{(group.status==="PARTIAL"||group.status==="CONFLICT")&&<div className="fiscal-alert">Há decisões anteriores diferentes. Salve uma decisão única para todas as linhas.</div>}
 {group.matchedProductId&&<div className="fiscal-suggestion semantic"><span>Produto sugerido · {group.productCandidates?.[0]?.confidenceLevel||"HIGH"}</span><strong>{group.matchedProductName}</strong>{group.productCandidates?.[0]?.reasons?.length?<ul>{group.productCandidates[0].reasons.map(r=><li key={r}>✓ {r}</li>)}</ul>:null}<button onClick={()=>{setAction("USE_EXISTING_PRODUCT");setSelected({id:group.matchedProductId!,name:group.matchedProductName!,brand:group.matchedProductBrand||"",gtin:group.gtin||"",quantityPerUnit:group.matchedProductQuantityPerUnit||0,unit:group.matchedProductUnit as UnitOfMeasure});}}>Usar sugestão</button></div>}
 {!!group.productCandidates?.slice(1).length&&<details className="other-candidates"><summary>Ver outras sugestões</summary>{group.productCandidates.slice(1).map(c=><button key={c.productId} onClick={()=>{setAction("USE_EXISTING_PRODUCT");setSelected({id:c.productId,name:c.displayName,brand:c.brand||"",gtin:"",quantityPerUnit:c.quantityPerUnit||0,unit:c.unit as UnitOfMeasure});}}><strong>{c.displayName}</strong><span>{c.confidenceLevel} · {c.reasons.join(" · ")}</span></button>)}</details>}
 <fieldset className="fiscal-decisions"><legend>O que fazer com este produto?</legend>{([["USE_EXISTING_PRODUCT","Usar produto existente"],["CREATE_TEMPORARY_PRODUCT","Criar produto temporário"],["EXPENSE_ONLY","Somente despesa"],["IGNORE","Ignorar"]] as const).map(([v,l])=><label key={v}><input type="radio" checked={action===v} onChange={()=>setAction(v)}/> {l}</label>)}</fieldset>
 {action==="USE_EXISTING_PRODUCT"&&<div className="product-picker">{selected&&<p className="selected-product">Selecionado: <strong>{selected.name}</strong> {selected.brand}</p>}<div className="product-search"><input aria-label="Buscar produto por nome" placeholder="Nome" value={name} onChange={e=>setName(e.target.value)}/><input aria-label="Buscar produto por GTIN" placeholder="GTIN" value={gtin} onChange={e=>setGtin(e.target.value)}/><button onClick={search}>Buscar</button></div>{!!results.length&&<div className="product-results">{results.map(p=><button key={p.id} onClick={()=>setSelected(p)}><strong>{p.name}</strong><span>{p.brand}</span></button>)}</div>}</div>}
 {action==="CREATE_TEMPORARY_PRODUCT"&&<div className="product-picker"><p><strong>Novo produto com dados detectados</strong></p><div className="product-search"><input aria-label="Nome do novo produto" value={tempName} onChange={e=>setTempName(e.target.value)}/><input aria-label="Marca do novo produto" placeholder="Marca" value={tempBrand} onChange={e=>setTempBrand(e.target.value)}/></div>{group.parsedDescriptor?.attributeTokens?.length?<p>Características: {group.parsedDescriptor.attributeTokens.join(", ")}</p>:null}</div>}
 {group.commercialUnitGroups.some(u=>u.contentEvidenceComparison?.status==="CONFLICT")&&<div className="content-conflict fiscal-alert"><strong>⚠ Encontramos uma diferença de conteúdo</strong>{group.commercialUnitGroups.filter(u=>u.contentEvidenceComparison?.status==="CONFLICT").map(u=><p key={u.commercialUnit}>Produto cadastrado: {u.contentEvidenceComparison?.productQuantity} {u.contentEvidenceComparison?.productUnit} · NFC-e: {u.contentEvidenceComparison?.descriptionQuantity} {u.contentEvidenceComparison?.descriptionUnit}</p>)}<label><input type="radio" name="content-resolution" onChange={()=>setContentResolution("USE_DESCRIPTION_CONTENT")}/> Usar o conteúdo da NFC-e nesta compra</label><label><input type="radio" name="content-resolution" onChange={()=>setContentResolution("USE_PRODUCT_CONTENT")}/> O cadastro atual está correto</label><label><input type="radio" name="content-resolution" onChange={()=>setContentResolution("CHOOSE_ANOTHER_PRODUCT")}/> Escolher outro produto</label></div>}
 {stocks(action)&&<section className="guided-quantity"><div className="guided-quantity-title"><div><strong>Conversão para a despensa</strong><p>Uma conversão para cada forma comercial.</p></div><button className="quantity-help-button" onClick={help}>? Como preencher?</button></div>{group.commercialUnitGroups.map(u=>{const d=drafts[u.commercialUnit];const known=u.commercialUnit==="UN"&&action==="USE_EXISTING_PRODUCT"&&selected?.quantityPerUnit&&selected?.unit&&!d.changed;const total=Number(u.totalQuantity)*Number(d?.units||0)*Number(d?.content||0);return <div className="commercial-conversion" key={u.commercialUnit}><strong>{decimal(u.totalQuantity)} {u.commercialUnit} · {u.lineCount} lançamento(s)</strong>{u.directMeasurement?<div className="quantity-result">Entrada automática: <strong>{decimal(u.totalQuantity)} {u.commercialUnit}</strong></div>:known?<div className="quantity-result">Conversão cadastrada: <strong>{decimal(Number(u.totalQuantity)*Number(selected?.quantityPerUnit))} {selected?.unit}</strong><button className="quantity-correction" onClick={()=>update(u.commercialUnit,{units:"1",content:String(selected?.quantityPerUnit||""),unit:selected?.unit||"",saveFuture:false})}>Corrigir somente nesta compra</button></div>:<>{u.learnedSuggestion&&!d.changed&&<div className="fiscal-suggestion"><span>Conversão aprendida</span><strong>{d.units} × {d.content} {d.unit}</strong><button onClick={()=>update(u.commercialUnit,{})}>Alterar</button></div>}<div className="stock-fields three"><label>Unidades por {u.commercialUnit}<input type="number" min="0" step="any" value={d.units} onChange={e=>update(u.commercialUnit,{units:e.target.value})}/></label><label>Conteúdo por unidade<input type="number" min="0" step="any" value={d.content} onChange={e=>update(u.commercialUnit,{content:e.target.value})}/></label><label>Unidade<select value={d.unit} onChange={e=>update(u.commercialUnit,{unit:e.target.value as UnitOfMeasure})}><option value="">Selecione</option>{units.map(x=><option key={x}>{x}</option>)}</select></label></div>{!!total&&d.unit&&<div className="quantity-calculation"><span>{decimal(u.totalQuantity)} × {d.units} × {d.content}</span><strong>Entrada: {decimal(total)} {d.unit}</strong></div>}<label className="save-conversion"><input type="checkbox" checked={d.saveFuture} onChange={e=>update(u.commercialUnit,{saveFuture:e.target.checked})}/> Usar em compras futuras deste estabelecimento</label></>}</div>;})}</section>}
 {error&&<div className="fiscal-alert" role="alert">{error}</div>}<div className="editor-actions"><button className="fiscal-secondary" onClick={cancel}>Cancelar</button><button className="fiscal-primary" disabled={busy} onClick={save}>{busy?"Salvando...":"Salvar grupo"}</button></div></div>;
};

const FiscalReceiptGroupedReview:React.FC=()=>{const {pantryId:p,importId:i}=useParams();const pantryId=Number(p),importId=Number(i),navigate=useNavigate();const [receipt,setReceipt]=useState<FiscalReceiptImportResponse|null>(null);const [expanded,setExpanded]=useState<string|null>(null);const [audit,setAudit]=useState<string|null>(null);const [help,setHelp]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(true);
 useEffect(()=>{fetchFiscalReceiptImport(importId).then(setReceipt).catch(e=>setError(fiscalReceiptErrorMessage(e))).finally(()=>setBusy(false));},[importId]);const groups=receipt?.reviewGroups||[];const resolved=groups.filter(g=>g.status==="SAVED").length;const lines=groups.filter(g=>g.status==="SAVED").reduce((n,g)=>n+g.lineCount,0);const canConfirm=groups.length>0&&groups.every(g=>g.status==="SAVED");const confirm=async()=>{if(!receipt||!window.confirm("Confirmar a compra e atualizar a despensa?"))return;setBusy(true);try{await confirmFiscalReceiptImport(receipt.id);navigate(`/pantry/${pantryId}`,{state:{fiscalReceiptConfirmed:true}});}catch(e){setError(fiscalReceiptErrorMessage(e));setBusy(false);}};
 if(busy&&!receipt)return <main className="fiscal-page"><p>Carregando nota...</p></main>;if(!receipt)return <main className="fiscal-page"><div className="fiscal-alert">{error||"Nota não encontrada."}</div></main>;
 return <main className="fiscal-page"><div className="fiscal-page-title"><div><span className="fiscal-kicker">Revisão da NFC-e #{receipt.id}</span><h1>{receipt.issuerName}</h1><p>{receipt.purchaseDate?new Date(receipt.purchaseDate).toLocaleString("pt-BR"):"Data não informada"} · {money(receipt.paidValue)}</p></div><div className="review-title-actions"><button className="quantity-help-button" onClick={()=>setHelp(true)}>? Como preencher?</button><button className="fiscal-secondary" onClick={()=>navigate(`/pantry/${pantryId}/fiscal-receipts`)}>Salvar e sair</button></div></div>
 <div className="review-summary"><strong>{resolved} de {groups.length} produtos revisados</strong><small>{lines} de {receipt.items.length} lançamentos fiscais resolvidos</small><div className="fiscal-progress"><span style={{width:`${groups.length?resolved*100/groups.length:0}%`}}/></div></div>{error&&<div className="fiscal-alert">{error}</div>}<div className="fiscal-items">{groups.map((g,index)=><article className={`fiscal-item ${g.status==="SAVED"?"resolved":""}`} key={g.reviewGroupId}><button className="item-summary" onClick={()=>setExpanded(expanded===g.reviewGroupId?null:g.reviewGroupId)}><span className="item-number">{index+1}</span><span className="item-description"><strong>{g.description}</strong><small>{g.commercialUnitGroups.map(u=>`${decimal(u.totalQuantity)} ${u.commercialUnit}`).join(" · ")} · {g.lineCount} lançamento(s) · {money(g.totalValue)}</small></span><span className="item-status">{{PENDING:"Pendente",PARTIAL:"Parcial",CONFLICT:"Conflito",SAVED:"Salvo"}[g.status]}</span></button><button className="audit-toggle" onClick={()=>setAudit(audit===g.reviewGroupId?null:g.reviewGroupId)}>Ver lançamentos da nota</button>{g.identityWarning&&<div className="fiscal-alert">Código com descrições incompatíveis: nenhum vínculo automático será aprendido.</div>}{audit===g.reviewGroupId&&<div className="fiscal-lines">{g.commercialUnitGroups.flatMap(u=>u.lines).map(line=><div key={line.id}><span>#{line.itemNumber} · {decimal(line.quantity)} {line.commercialUnit}</span><span>{money(line.totalPrice)} · {line.resolutionAction||"Sem decisão"}</span></div>)}</div>}{expanded===g.reviewGroupId&&<GroupEditor importId={receipt.id} group={g} help={()=>setHelp(true)} cancel={()=>setExpanded(null)} saved={r=>{setReceipt(r);setExpanded(null);}}/>}</article>)}</div><div className="confirm-bar"><div><strong>{canConfirm?"Revisão completa":"Ainda existem produtos pendentes"}</strong><p>Os lançamentos fiscais originais serão preservados.</p></div><button className="fiscal-primary" disabled={!canConfirm||busy} onClick={confirm}>Confirmar compra</button></div><FiscalQuantityHelpModal open={help} onClose={()=>setHelp(false)}/></main>;
};
export default FiscalReceiptGroupedReview;
